### ISSUE TITLE
502 bad gateway if nginx as gateway for jenkins

### ISSUE THREAD

**Issue by csheller** [bndynet/spring-cloud-starter#2]
When I use nginx as gateway for jenkins and `mvn clean package -Pwar`, throws bellow error in **Console** in jenkins build.

```
502 bad gateway
```

**Comment by bndynet** [comment]
Change nginx configuration as below
```
server {

    listen 80;
    server_name jenkins.domain.net;
     
    location / {
      ...
      # default is 60s,  but you can set 600s
      proxy_read_timeout  600;
```

https://wiki.jenkins.io/display/JENKINS/Jenkins+behind+an+NGinX+reverse+proxy
